version: '3'

services:
  node:
    &node
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    command: npm start
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
